In [1]:
import numpy as np

In [3]:
x=np.array([1,2,3,4])

In [4]:
x

array([1, 2, 3, 4])

In [5]:
type(x)

numpy.ndarray

In [6]:
y=np.array([23,45,78,1])

In [7]:
y

array([23, 45, 78,  1])

In [8]:
y.shape

(4,)

In [9]:
y.size

4

In [10]:
z=np.array([[1,2,3],[4,5,6]])

In [11]:
z

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
z.shape

(2, 3)

In [13]:
z.size

6

In [14]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [15]:
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [16]:
a.shape

(1, 3, 3)

In [17]:
a.ndim

3

In [18]:
x

array([1, 2, 3, 4])

In [19]:
x[2]

3

In [21]:
z



array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
z[0:2,1:1]


array([], shape=(2, 0), dtype=int32)

In [35]:
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [37]:
a[0,2,1]

8

In [42]:
z=np.zeros([3,3])

In [43]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
d=np.zeros([0,0])

In [48]:
d

array([], shape=(0, 0), dtype=float64)

In [52]:
X=np.ones(5)

In [53]:
X

array([1., 1., 1., 1., 1.])

In [54]:
Y=np.ones([0])

In [55]:
Y

array([], dtype=float64)

In [61]:
Z=np.ones([2,0])

In [62]:
Z

array([], shape=(2, 0), dtype=float64)

In [63]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [64]:
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [69]:
s=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [70]:
s

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
s.sum(axis=0)

array([12, 15, 18])

In [72]:
s.sum(axis=1)

array([ 6, 15, 24])

In [76]:
r=np.arange(50)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [78]:
f=np.arange(0,20)
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])